default: &default
  adapter: mysql2
  username: root
  password:
  host: 127.0.0.1
  encoding: utf8

development:
  <<: *default
  database: devf_development
test:
  <<: *default
  database: devf_test
production:
  <<: *default
  database: devf_production
