-
  question: "En que programa te interesa participar"
  type: select
  choices:
    - Cinta Blanca
    - Cinta Roja
	- Cinta Negra
-
  question: "Nombre"
  type: name
-
  question: "Email"
  type: email
-
  question: "Teléfono"
  type: phone
-
  question: "¿En qué parte de México o del mundo vives? (si vives en el DF, incluir delegación y zona)"
  type: text_area
-
  question: "¿Por qué quieres entrar a Dev.F.?"
  type: text_area
-
  question: "Platícanos sobre un fracaso o fuck-up grande que tuviste y sobre el aprendizaje que te dejó."
  type: text_area
-
  question: "¿Qué te ves haciendo en 2 años?"
  type: text_area
-
  question: "¿Qué logro te ha hecho sentir más orgulloso?"
  type: text_area
-
  question: "¿Qué personaje admiras? ¿Por qué?"
  type: text_area
-
  question: "¿Qué haces en tu tiempo libre?"
  type: text_area
-
  question: "¿Qué herramientas te gusta utilizar en tu ocupación diaria? ¿Por qué?"
  type: text_area
-
  question: "¿A qué te dedicarías si vivieras en la época de Leonardo Da Vinci?"
  type: text_area