
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  github_key: <%= ENV["GITHUB_KEY"] %>
  github_secret: <%= ENV["GITHUB_SECRET"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>


development:
  secret_key_base: 75632f9b378c7033afb1c2d48456c635542cfe473d9fdc7aa73067e56e68a754ea5c262092dc185783a6d5c9cfe70a688ab294699527531ca91d2d7f39939f8b
  twitter_key: D13OLdWHqIuT3dPZsXoDqt3kB
  twitter_secret: xiUaC3Fovk3irENCwU6raN8iCNLubfvY1K9D4w3X2jMEep9Uwh
  facebook_key: 1615415365349406
  facebook_secret: 4981812b225da679ab50eb4a2285f8c2
  github_key: a3f757aec0a9e63fdfe9
  github_secret: a9e99012b4b99447a58401915caeb937fe7d66d8
  smtp_password:

test:
  secret_key_base: 09714b06e63b020cc6fb49b1a0b229fc724fba85e2a094a8d8ea7d9b7f13a4ce926f7716711aace787faa7f9d7cd10474b75526dc99105f8bc22fcb4fe9debac
