<%
developer_name = %x(git config user.name).chomp rescue "developer"
developer_email = %x(git config user.email).chomp rescue "developer@devf.test"
%>
common: &common
  developer_name: "<%= developer_name %>"
  developer_email: "<%= developer_email %>"
  tagline: "desarrollamos(developers);"
  interesting_links:
    "The Hacker Attitude": "http://www.catb.org/esr/faqs/hacker-howto.html#attitude"
    "Great Hackers": "http://www.paulgraham.com/gh.html"
  slack:
    team: devf
    hook: incoming-webhook
    test: '#prueba'
    exception_ocurred:
      channel: 'site-exceptions'
      username: "Boomer"
    user_registered:
      channel: "site-notifications" 
    application_received:
      channel: "site-notifications"
    application_decided:
      channel: 'site-notifications'
    application_rated:
      channel: 'site-notifications'

development:
  <<: *common
  domain: "devf.dev"
  smtp_settings:
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "gmail.com"
    :user_name: "devf.hackers@gmail.com"
    :authentication: plain
    :enable_starttls_auto: true

test:
  <<: *common
  domain: "devf.test"
  smtp_settings:

production:
  <<: *common
  domain: "devf.mx"
  # domain: "devf-site.herokuapp.com"
  smtp_settings:
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "devf.mx"
    # :domain: "devf-site.herokuapp.com"
    :user_name: "noreply@devf.mx"
    :authentication: plain
    :enable_starttls_auto: true
