<%

if Rails.env.development?
  domain = 'devf.dev'
  dev_mail = %x(git config user.email).chomp
elsif Rails.env.test?
  domain = 'devf.test' 
elsif Rails.env.production?
  domain = 'devf.mx'
end

contact_email = dev_mail || "hola@#{domain}"
support_email = dev_mail || "hola@#{domain}"

error_notifications_to = [ contact_email ]
notify_postulations_to = [ contact_email ]
if Rails.env.production?
  notify_postulations_to = [ "hola@#{domain}" ]
  error_notifications_to = [ "vic.borja@gmail.com" ]
end

%>
common: &common
  domain: "<%= domain %>"
  contact_email: "<%= contact_email %>"
  support_email: "<%= support_email %>"
  error_notifications_to:
    <% error_notifications_to.each do |mail| %>
    - "<%= mail %>"
    <% end %>
  notify_postulations_to:
    <% notify_postulations_to.each do |mail| %>
    - "<%= mail %>"
    <% end %>
  default_url_options:
    :host: "<%= domain %>"
  slack:
    team: devf
    hook: incoming-webhook
    test: '#prueba'
    exception_ocurred:
      channel: '#sitio-web-devf'
      username: "Boomer"
    new_user_registered:
      channel: "#general"
    application_received:
      channel: "#general"
    application_decided:
      channel: '#general'
    application_rated:
      channel: '#general'
development:
  <<: *common
  smtp_settings:
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "gmail.com"
    :user_name: "devf.hackers@gmail.com"
    :password: "<%= Rails.application.secrets.smtp_password %>"
    :authentication: plain
    :enable_starttls_auto: true

test:
  <<: *common
  smtp_settings:

production:
  <<: *common
  smtp_settings:
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "devf.mx"
    :user_name: "noreply@devf.mx"
    :password: "<%= Rails.application.secrets.smtp_password %>"
    :authentication: plain
    :enable_starttls_auto: true
