<%
developer_name = %x(git config user.name).chomp rescue "developer"
developer_email = %x(git config user.email).chomp rescue "developer@devf.test"
%>
common: &common
  developer_name: "<%= developer_name %>"
  developer_email: "<%= developer_email %>"
  slack:
    team: devf
    hook: incoming-webhook
    test: '#prueba'
    exception_ocurred:
      channel: '#sitio-web-devf'
      username: "Boomer"
    new_user_registered:
      channel: "#general"
    application_received:
      channel: "#general"
    application_decided:
      channel: '#general'
    application_rated:
      channel: '#general'

development:
  <<: *common
  domain: "devf.dev"
  smtp_settings:
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "gmail.com"
    :user_name: "devf.hackers@gmail.com"
    :authentication: plain
    :enable_starttls_auto: true

test:
  <<: *common
  domain: "devf.test"
  smtp_settings:

production:
  <<: *common
  domain: "devf.mx"
  smtp_settings:
    :address: "smtp.gmail.com"
    :port: 587
    :domain: "devf.mx"
    :user_name: "noreply@devf.mx"
    :authentication: plain
    :enable_starttls_auto: true
